/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('kaizen').del();
  await knex('kaizen').insert([
    {
      id: 1,
      date: '20251117',
      name: '渡辺',
      number: 57463,
      department: '吉原組立',
      theme: 'からくり改善',
      before: '重量物を持っていた',
      after: '設備で交換する',
      solution: '設備作成',
      Effect_Amount: 30000,
      safe: true,
      quality: true,
      man_Hour: 2400,
    },
    {
      id: 2,
      date: '20251116',
      name: '佐藤',
      number: 48211,
      department: 'いなべ塗装',
      theme: '動線短縮',
      before: '部品棚が遠く取りに行く必要があった',
      after: '棚位置を工程横に変更',
      solution: 'レイアウト改善',
      Effect_Amount: 12000,
      safe: true,
      quality: false,
      man_Hour: 1800,
    },
    {
      id: 3,
      date: '20251115',
      name: '高橋',
      number: 59324,
      department: '吉原車体',
      theme: 'からくり改善',
      before: '部材を手で押し込んでいた',
      after: 'ばね機構で自動押し込み',
      solution: '治具追加',
      Effect_Amount: 25000,
      safe: false,
      quality: true,
      man_Hour: 2000,
    },
    {
      id: 4,
      date: '20251118',
      name: '田中',
      number: 51233,
      department: 'いなべ塗装',
      theme: '不良低減',
      before: '部品が傾いてセットされることがあった',
      after: 'ガイドを追加して位置決めを安定',
      solution: 'ガイド治具製作',
      Effect_Amount: 18000,
      safe: true,
      quality: true,
      man_Hour: 1500,
    },
    {
      id: 5,
      date: '20251114',
      name: '伊藤',
      number: 46392,
      department: '吉原組立',
      theme: '搬送改善',
      before: '台車が重く押しにくい',
      after: 'キャスター交換で軽く移動可能に',
      solution: 'キャスター改善',
      Effect_Amount: 8000,
      safe: false,
      quality: false,
      man_Hour: 1300,
    },
    {
      id: 6,
      date: '20251113',
      name: '山本',
      number: 55127,
      department: 'いなべ組立',
      theme: '作業標準化',
      before: '手順が人によりバラバラ',
      after: '標準書と動画作成',
      solution: '標準化作業',
      Effect_Amount: 9000,
      safe: true,
      quality: true,
      man_Hour: 1000,
    },
    {
      id: 7,
      date: '20251112',
      name: '中村',
      number: 47288,
      department: '吉原塗装',
      theme: '品質向上',
      before: '塗布量が安定しない',
      after: 'ノズルに調整治具を導入',
      solution: '治具作成',
      Effect_Amount: 15000,
      safe: false,
      quality: true,
      man_Hour: 1700,
    },
    {
      id: 8,
      date: '20251111',
      name: '小林',
      number: 49811,
      department: '吉原車体',
      theme: '設備改善',
      before: '設備停止が多かった',
      after: 'センサー位置を最適化',
      solution: 'センサー調整',
      Effect_Amount: 22000,
      safe: true,
      quality: true,
      man_Hour: 2100,
    },
    {
      id: 9,
      date: '20251110',
      name: '加藤',
      number: 51124,
      department: '吉原組立',
      theme: '作業削減',
      before: '部品を都度取りに行く必要があった',
      after: '手元にストックボックス配置',
      solution: '棚追加',
      Effect_Amount: 5000,
      safe: false,
      quality: false,
      man_Hour: 900,
    },
    {
      id: 10,
      date: '20251109',
      name: '山田',
      number: 47321,
      department: 'いなべ車体',
      theme: 'からくり改善',
      before: '治具を手で固定していた',
      after: 'スプリング機構で自動固定',
      solution: '簡易からくり',
      Effect_Amount: 28000,
      safe: true,
      quality: true,
      man_Hour: 2300,
    },
    {
      id: 11,
      date: '20251118',
      name: '松本',
      number: 55672,
      department: '吉原組立',
      theme: '動線改善',
      before: '部材取りに5m歩いていた',
      after: '棚位置変更で1mに短縮',
      solution: '配置改善',
      Effect_Amount: 16000,
      safe: false,
      quality: true,
      man_Hour: 1200,
    },
    {
      id: 12,
      date: '20251117',
      name: '井上',
      number: 49533,
      department: '吉原塗装',
      theme: '設備改善',
      before: 'エア圧が不安定',
      after: '配管清掃とバルブ交換',
      solution: '設備メンテ',
      Effect_Amount: 19000,
      safe: true,
      quality: true,
      man_Hour: 2000,
    },
    {
      id: 13,
      date: '20251116',
      name: '木村',
      number: 52531,
      department: 'いなべ組立',
      theme: '省人化',
      before: '2人作業だった',
      after: '治具導入で1人作業化',
      solution: '治具作成',
      Effect_Amount: 45000,
      safe: true,
      quality: true,
      man_Hour: 3000,
    },
    {
      id: 14,
      date: '20251115',
      name: '林',
      number: 47428,
      department: '吉原車体',
      theme: '品質改善',
      before: '溶接ずれが発生',
      after: 'ガイドピン追加',
      solution: 'ガイド治具作成',
      Effect_Amount: 20000,
      safe: false,
      quality: true,
      man_Hour: 1600,
    },
    {
      id: 15,
      date: '20251114',
      name: '清水',
      number: 49755,
      department: 'いなべ塗装',
      theme: 'からくり改善',
      before: '箱の持ち上げが重い',
      after: '傾斜台で自然降下',
      solution: 'からくり台作成',
      Effect_Amount: 23000,
      safe: true,
      quality: false,
      man_Hour: 1900,
    },
    {
      id: 16,
      date: '20251113',
      name: '山崎',
      number: 45239,
      department: 'いなべ組立',
      theme: '部品供給改善',
      before: '供給タイミングがズレる',
      after: '定量供給ボックス導入',
      solution: 'ボックス作成',
      Effect_Amount: 17000,
      safe: false,
      quality: true,
      man_Hour: 1400,
    },
    {
      id: 17,
      date: '20251112',
      name: '森',
      number: 54830,
      department: '吉原組立',
      theme: '作業性向上',
      before: 'ネジ締め姿勢が悪かった',
      after: '高さ調整台導入',
      solution: '作業台改造',
      Effect_Amount: 13000,
      safe: true,
      quality: false,
      man_Hour: 1100,
    },
    {
      id: 18,
      date: '20251111',
      name: '橋本',
      number: 51192,
      department: 'いなべ塗装',
      theme: '品質改善',
      before: '色ムラが出る',
      after: '吹付距離を自動調整',
      solution: 'ガイド改善',
      Effect_Amount: 26000,
      safe: false,
      quality: true,
      man_Hour: 2100,
    },
    {
      id: 19,
      date: '20251110',
      name: '阿部',
      number: 46420,
      department: '吉原車体',
      theme: '設備改善',
      before: '溶接治具が重い',
      after: '軽量化設計',
      solution: '治具改良',
      Effect_Amount: 15000,
      safe: true,
      quality: true,
      man_Hour: 1700,
    },
    {
      id: 20,
      date: '20251109',
      name: '石川',
      number: 57321,
      department: '吉原塗装',
      theme: '動線短縮',
      before: '材料取りに時間がかかっていた',
      after: '棚の回転式化',
      solution: '回転棚導入',
      Effect_Amount: 21000,
      safe: false,
      quality: true,
      man_Hour: 2000,
    },
    {
      id: 21,
      date: '20251118',
      name: '中島',
      number: 50011,
      department: 'いなべ車体',
      theme: '省力化',
      before: '溶接トーチを手で保持',
      after: 'アーム支持台追加',
      solution: '保持治具作成',
      Effect_Amount: 18000,
      safe: true,
      quality: true,
      man_Hour: 1500,
    },
    {
      id: 22,
      date: '20251117',
      name: '前田',
      number: 48012,
      department: '吉原組立',
      theme: 'からくり改善',
      before: '箱の位置合わせに時間がかかる',
      after: '自重で位置決めする台を作成',
      solution: '簡易治具',
      Effect_Amount: 24000,
      safe: true,
      quality: false,
      man_Hour: 1700,
    },
    {
      id: 23,
      date: '20251116',
      name: '藤田',
      number: 47029,
      department: 'いなべ塗装',
      theme: '品質改善',
      before: '塗料の吐出量にばらつき',
      after: '自動調整装置追加',
      solution: 'センサー追加',
      Effect_Amount: 30000,
      safe: false,
      quality: true,
      man_Hour: 2200,
    },
    {
      id: 24,
      date: '20251115',
      name: '岡田',
      number: 52391,
      department: 'いなべ車体',
      theme: '作業標準化',
      before: '検査基準が曖昧',
      after: '検査画像付きマニュアル化',
      solution: '標準書作成',
      Effect_Amount: 12000,
      safe: false,
      quality: true,
      man_Hour: 900,
    },
    {
      id: 25,
      date: '20251114',
      name: '三浦',
      number: 55382,
      department: '吉原塗装',
      theme: '作業削減',
      before: '部品清掃に手作業が必要',
      after: '自動エアブロー追加',
      solution: '自動化',
      Effect_Amount: 14000,
      safe: true,
      quality: false,
      man_Hour: 1000,
    },
    {
      id: 26,
      date: '20251113',
      name: '原田',
      number: 46200,
      department: '吉原組立',
      theme: 'からくり改善',
      before: 'ボルト供給が不安定',
      after: '傾斜供給ガイドを追加',
      solution: '傾斜ガイド',
      Effect_Amount: 20000,
      safe: true,
      quality: true,
      man_Hour: 1600,
    },
    {
      id: 27,
      date: '20251112',
      name: '小川',
      number: 57411,
      department: 'いなべ車体',
      theme: '品質改善',
      before: '溶接スパッタが多い',
      after: 'ノズル清掃の頻度UP',
      solution: '清掃標準化',
      Effect_Amount: 10000,
      safe: true,
      quality: true,
      man_Hour: 800,
    },
    {
      id: 28,
      date: '20251111',
      name: '村上',
      number: 52388,
      department: '吉原組立',
      theme: '動線改善',
      before: '治具置場が遠い',
      after: '工程横に置場を移設',
      solution: 'レイアウト改善',
      Effect_Amount: 9000,
      safe: false,
      quality: false,
      man_Hour: 700,
    },
    {
      id: 29,
      date: '20251110',
      name: '近藤',
      number: 49312,
      department: '吉原塗装',
      theme: '設備改善',
      before: '冷却時間が長かった',
      after: '冷却効率UPのノズルに変更',
      solution: 'ノズル交換',
      Effect_Amount: 21000,
      safe: false,
      quality: true,
      man_Hour: 2000,
    },
    {
      id: 30,
      date: '20251109',
      name: '石井',
      number: 58533,
      department: 'いなべ組立',
      theme: 'からくり改善',
      before: '部品の滑り落ちが発生',
      after: 'ストッパー追加',
      solution: '簡易ストッパー',
      Effect_Amount: 8000,
      safe: true,
      quality: true,
      man_Hour: 900,
    },
    {
      id: 31,
      date: '20251117',
      name: '柴田',
      number: 46455,
      department: '吉原組立',
      theme: '作業性向上',
      before: 'ネジ締め工具が遠い',
      after: '工具移動',
      solution: '配置替え',
      Effect_Amount: 6000,
      safe: false,
      quality: false,
      man_Hour: 700,
    },
    {
      id: 32,
      date: '20251116',
      name: '安藤',
      number: 53012,
      department: '吉原塗装',
      theme: '品質改善',
      before: 'ミストの飛散が多い',
      after: 'ガード設置',
      solution: 'ガード作成',
      Effect_Amount: 15000,
      safe: true,
      quality: true,
      man_Hour: 1300,
    },
    {
      id: 33,
      date: '20251115',
      name: '宮崎',
      number: 58421,
      department: 'いなべ塗装',
      theme: '設備改善',
      before: '成形品の反りが多い',
      after: '冷却均一化',
      solution: '改善ノズル',
      Effect_Amount: 25000,
      safe: false,
      quality: true,
      man_Hour: 2000,
    },
    {
      id: 34,
      date: '20251114',
      name: '宮本',
      number: 47733,
      department: '吉原車体',
      theme: 'からくり改善',
      before: '上げ下げが重い',
      after: 'バネ式リフト導入',
      solution: '簡易リフト',
      Effect_Amount: 28000,
      safe: true,
      quality: false,
      man_Hour: 2200,
    },
    {
      id: 35,
      date: '20251113',
      name: '市川',
      number: 49827,
      department: '吉原組立',
      theme: '動線短縮',
      before: 'ボルト取り出しに歩く必要',
      after: '手元にラック設置',
      solution: '棚移動',
      Effect_Amount: 11000,
      safe: false,
      quality: false,
      man_Hour: 1000,
    },
    {
      id: 36,
      date: '20251112',
      name: '山内',
      number: 46499,
      department: 'いなべ塗装',
      theme: '品質改善',
      before: '色ムラの再発',
      after: '吹き方をガイド化',
      solution: '治具作成',
      Effect_Amount: 19000,
      safe: true,
      quality: true,
      man_Hour: 1300,
    },
    {
      id: 37,
      date: '20251111',
      name: '池田',
      number: 54322,
      department: '吉原組立',
      theme: '設備改善',
      before: '設備停止が多い',
      after: '配線の取り回し改善',
      solution: '配線修正',
      Effect_Amount: 21000,
      safe: true,
      quality: true,
      man_Hour: 1600,
    },
    {
      id: 38,
      date: '20251110',
      name: '長谷川',
      number: 53211,
      department: '吉原塗装',
      theme: '搬送改善',
      before: '搬送中の振動が大きい',
      after: '防振材追加',
      solution: '台車改良',
      Effect_Amount: 9000,
      safe: false,
      quality: true,
      man_Hour: 1200,
    },
    {
      id: 39,
      date: '20251109',
      name: '岡本',
      number: 57552,
      department: 'いなべ車体',
      theme: 'からくり改善',
      before: '部品落下が多い',
      after: 'ガイドレール追加',
      solution: 'レール作成',
      Effect_Amount: 17000,
      safe: true,
      quality: true,
      man_Hour: 1500,
    },
    {
      id: 40,
      date: '20251118',
      name: '竹内',
      number: 51290,
      department: '吉原塗装',
      theme: '品質改善',
      before: '塗り残しが発生',
      after: 'ライト追加で視認性UP',
      solution: '照明改善',
      Effect_Amount: 12000,
      safe: false,
      quality: true,
      man_Hour: 1100,
    },
    {
      id: 41,
      date: '20251117',
      name: '金子',
      number: 56344,
      department: 'いなべ組立',
      theme: '作業性向上',
      before: '姿勢が悪く腰痛発生',
      after: '作業台高さ調整',
      solution: '作業台改良',
      Effect_Amount: 15000,
      safe: true,
      quality: false,
      man_Hour: 1500,
    },
    {
      id: 42,
      date: '20251116',
      name: '西村',
      number: 58621,
      department: '吉原塗装',
      theme: 'からくり改善',
      before: 'ケースを毎回持ち上げていた',
      after: '滑り台で自然移動',
      solution: '滑り台改善',
      Effect_Amount: 22000,
      safe: true,
      quality: false,
      man_Hour: 1800,
    },
    {
      id: 43,
      date: '20251115',
      name: '菅原',
      number: 51235,
      department: '吉原車体',
      theme: '設備改善',
      before: '治具の位置決めが難しい',
      after: 'ピン位置変更で安定',
      solution: '治具改良',
      Effect_Amount: 20000,
      safe: true,
      quality: true,
      man_Hour: 1900,
    },
    {
      id: 44,
      date: '20251114',
      name: '藤原',
      number: 47480,
      department: 'いなべ塗装',
      theme: '品質改善',
      before: 'バリ発生が多い',
      after: '型温度調整',
      solution: '温度改善',
      Effect_Amount: 14000,
      safe: false,
      quality: true,
      man_Hour: 1200,
    },
    {
      id: 45,
      date: '20251113',
      name: '松田',
      number: 48890,
      department: '吉原組立',
      theme: '動線改善',
      before: '歩行距離が長い',
      after: '部品棚の近接化',
      solution: '配置替え',
      Effect_Amount: 8000,
      safe: false,
      quality: false,
      man_Hour: 900,
    },
    {
      id: 46,
      date: '20251112',
      name: '森田',
      number: 57488,
      department: '吉原塗装',
      theme: '設備改善',
      before: '部品乾燥が遅い',
      after: '温風機導入',
      solution: '乾燥工程改善',
      Effect_Amount: 26000,
      safe: true,
      quality: true,
      man_Hour: 2100,
    },
    {
      id: 47,
      date: '20251111',
      name: '青木',
      number: 53091,
      department: 'いなべ塗装',
      theme: '作業削減',
      before: '保護テープ貼りに時間',
      after: '治具で貼付簡易化',
      solution: '貼付治具',
      Effect_Amount: 11000,
      safe: false,
      quality: true,
      man_Hour: 1000,
    },
    {
      id: 48,
      date: '20251110',
      name: '池上',
      number: 45220,
      department: '吉原組立',
      theme: 'からくり改善',
      before: '箱の取り出しがしにくい',
      after: '傾斜棚導入',
      solution: '棚改良',
      Effect_Amount: 15000,
      safe: true,
      quality: false,
      man_Hour: 1600,
    },
    {
      id: 49,
      date: '20251109',
      name: '岩田',
      number: 52477,
      department: '吉原組立',
      theme: '動線短縮',
      before: 'QC工具を取りに行く必要',
      after: '工具ワゴン導入',
      solution: 'ワゴン作成',
      Effect_Amount: 7000,
      safe: false,
      quality: false,
      man_Hour: 800,
    },
    {
      id: 50,
      date: '20251118',
      name: '平野',
      number: 56301,
      department: 'いなべ車体',
      theme: '品質改善',
      before: '溶接角度が不安定',
      after: '固定ガイド追加',
      solution: 'ガイド作成',
      Effect_Amount: 20000,
      safe: true,
      quality: true,
      man_Hour: 1800,
    },
  ]);
};
